In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
select_data=pd.read_csv("keerthi_data.csv")
select_data.head()


make peak-rpm curb-weight  ... horsepower city-mpg  price
0  alfa-romero     5000        2548  ...        111       21  13495
1  alfa-romero     5000        2823  ...        111       21  16500
2  alfa-romero     5500        2337  ...        154       19  16500
3         audi        ?        2824  ...        102       24  13950
4         audi     5500        2507  ...        115       18  17450

[5 rows x 11 columns]

In [ ]:
import numpy as np
np.random.seed(seed = 111)
random_numbers = list(np.random.random_integers(low = 1,high = 9,size = 3))
random_chars = []
for i in range(5):
  random_chars.append(np.random.choice(np.array(['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'])))
overall_otp = random_chars + random_numbers
#print(overall_otp)
final_code = ["".join(str(overall_otp[i])) for i in range(len(overall_otp))]  
#print(final_code) 
final_str =''
for i in final_code:
  final_str = final_str+i
final_str

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 9 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


'wtjcw555'

In [ ]:
import numpy as np
np.random.seed(seed = 111)
random_numbers = list(np.random.random_integers(low = 1,high = 9,size = 3))
np.random.rand(5)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 9 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until


array([0.43605902, 0.76926247, 0.2953253 , 0.14916296, 0.02247832])

In [ ]:
np.random.rand(50)

array([0.43605902, 0.76926247, 0.2953253 , 0.14916296, 0.02247832,
       0.42022449, 0.23868214, 0.33765619, 0.99071246, 0.23772645,
       0.08119266, 0.66960024, 0.62124292, 0.27425353, 0.46622141,
       0.11836775, 0.07395756, 0.90077418, 0.79396256, 0.84056965,
       0.81520746, 0.99095485, 0.57727383, 0.81376692, 0.42131788,
       0.02744796, 0.45413664, 0.10532609, 0.81722006, 0.69772773,
       0.5652854 , 0.2742273 , 0.99847374, 0.13804205, 0.61541569,
       0.4850363 , 0.40502704, 0.7278491 , 0.32281393, 0.40054555,
       0.3189664 , 0.94722183, 0.91870836, 0.81384438, 0.03407709,
       0.94337287, 0.95043916, 0.80659105, 0.48127804, 0.96675923])

In [ ]:
np.random.randint(low=1,high=999,size=5)

array([ 43, 681, 429, 378, 178])

In [ ]:
np.random.random_sample([10])

array([0.62078363, 0.3159007 , 0.26304076, 0.81367862, 0.81581445,
       0.59314367, 0.5103815 , 0.37864191, 0.41915008, 0.89485045])